{"level":30,"time":1640529304937,"pid":10976,"hostname":"DESKTOP-GMEH9MC","msg":"Server listening at http://127.0.0.1:4000"}
{"level":30,"time":1640529314719,"pid":1888,"hostname":"DESKTOP-GMEH9MC","msg":"Server listening at http://127.0.0.1:4000"}
[14:35:34 UTC] INFO: Server listening at http://127.0.0.1:4000
[14:35:45 UTC] INFO: incoming request
    reqId: "req-1"
    req: {
      "method": "GET",
      "url": "/?users=123&name=ali",
      "parameters": {},
      "queryParams": {
        "users": "123",
        "name": "ali"
      }
    }
[14:35:45 UTC] INFO: Route GET:/?users=123&name=ali not found
    reqId: "req-1"
[14:35:45 UTC] INFO: request completed
    reqId: "req-1"
    res: {
      "statusCode": 404
    }
    responseTime: 12.223795998841524
[14:37:16 UTC] INFO: Server listening at http://127.0.0.1:4000
[14:38:58 UTC] INFO: Server listening at http://127.0.0.1:4000
[14:39:13 UTC] INFO: incoming request
    reqId: "req-1"
    req: {
      "method": "GET",
      "url": "/users/17af78ee-3c30-4ec1-a849-53907e37199d1",
      "parameters": {
        "id": "17af78ee-3c30-4ec1-a849-53907e37199d1"
      },
      "queryParams": {}
    }
[14:39:13 UTC] WARN: Reply already sent
    reqId: "req-1"
    err: {
      "type": "FastifyError",
      "message": "Reply was already sent.",
      "stack":
          FastifyError: Reply was already sent.
              at _Reply.Reply.send (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\reply.js:124:26)
              at Object.getSingleItem (D:\Nodejs2021Q4-service\nodejs2021Q4-service\src\resources\users\user.service.ts:50:9)
              at preHandlerCallback (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\handleRequest.js:126:28)
              at next (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\hooks.js:158:7)
              at Object.<anonymous> (D:\Nodejs2021Q4-service\nodejs2021Q4-service\src\server.ts:37:5)
              at hookIterator (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\hooks.js:237:10)
              at next (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\hooks.js:164:16)
              at hookRunner (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\hooks.js:187:3)
              at preValidationCallback (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\handleRequest.js:101:5)
              at handler (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\handleRequest.js:72:7)
      "name": "FastifyError",
      "code": "FST_ERR_REP_ALREADY_SENT",
      "statusCode": 500
    }
[14:39:13 UTC] INFO: request completed
    reqId: "req-1"
    res: {
      "statusCode": 404
    }
    responseTime: 66.7282490003854
[14:40:48 UTC] INFO: Server listening at http://127.0.0.1:4000
[14:40:53 UTC] INFO: incoming request
    reqId: "req-1"
    req: {
      "method": "GET",
      "url": "/users/17af78ee-3c30-4ec1-a849-53907e37199d1",
      "parameters": {
        "id": "17af78ee-3c30-4ec1-a849-53907e37199d1"
      },
      "queryParams": {}
    }
[14:40:53 UTC] WARN: Reply already sent
    reqId: "req-1"
    err: {
      "type": "FastifyError",
      "message": "Reply was already sent.",
      "stack":
          FastifyError: Reply was already sent.
              at _Reply.Reply.send (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\reply.js:124:26)
              at Object.getSingleItem (D:\Nodejs2021Q4-service\nodejs2021Q4-service\src\resources\users\user.service.ts:50:9)
              at preHandlerCallback (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\handleRequest.js:126:28)
              at next (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\hooks.js:158:7)
              at Object.<anonymous> (D:\Nodejs2021Q4-service\nodejs2021Q4-service\src\server.ts:37:5)
              at hookIterator (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\hooks.js:237:10)
              at next (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\hooks.js:164:16)
              at hookRunner (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\hooks.js:187:3)
              at preValidationCallback (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\handleRequest.js:101:5)
              at handler (D:\Nodejs2021Q4-service\nodejs2021Q4-service\node_modules\fastify\lib\handleRequest.js:72:7)
      "name": "FastifyError",
      "code": "FST_ERR_REP_ALREADY_SENT",
      "statusCode": 500
    }
[14:40:53 UTC] INFO: request completed
    reqId: "req-1"
    res: {
      "statusCode": 200
    }
    responseTime: 32.306081999093294
[14:41:10 UTC] INFO: Server listening at http://127.0.0.1:4000
